#!/bin/csh -f

set output = station_map.eps

# Small map
set x1 = -126
set x2 = -120
set y1 = 38
set y2 = 42
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123/40/3.5

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

gmt psxy permanent.txt -R$Rop -J$Jop -St0.5 -Gred -O -K >> $output

gmt psxy FAME.txt -R$Rop -J$Jop -St0.5 -Gblue -O -K >> $output

# Large map
set x1 = -130
set x2 = -115
set y1 = 35
set y2 = 50
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123/40/0.4

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::wEsN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X0.5 -Y0.5 -O -K >> $output

# Location of small map
cat << END >> square.dat
-126 42
-126 38
-120 38
-120 42
-126 42
END

gmt psxy square.dat -R$Rop -J$Jop -Wthicker,red -O >> $output

rm square.dat
