#!/bin/csh -f

set output = california.eps

# Small map
set x1 = -125
set x2 = -122
set y1 = 39
set y2 = 42
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.5/40.5/5.0

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

#gmt psxy plourde0.txt -R$Rop -J$Jop -Sc0.2 -Ggrey -O -K >> $output
gmt psxy plourde1.txt -R$Rop -J$Jop -Sc0.2 -Gred -O -K >> $output
gmt psxy plourde2.txt -R$Rop -J$Jop -Sc0.2 -Gorange -O -K >> $output
gmt psxy plourde3.txt -R$Rop -J$Jop -Sc0.2 -Ggreen -O -K >> $output
#gmt psxy plourde4.txt -R$Rop -J$Jop -Sc0.2 -Gcyan -O -K >> $output
#gmt psxy plourde5.txt -R$Rop -J$Jop -Sc0.2 -Gblue -O -K >> $output


# Large map
set x1 = -130
set x2 = -116
set y1 = 35
set y2 = 47
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.5/40.5/0.5

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::wEsN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X0.5 -Y0.5 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-123.5 40.5
END

cat << END >> names.dat
-126 41 Cape
-126 39.5 Mendocino
END

gmt psxy zoom.dat -R$Rop -J$Jop -Sc0.3 -Gblack -O -K >> $output

gmt pstext names.dat -R$Rop -J$Jop -F+f15p,black -O >> $output

rm names.dat
rm zoom.dat
