#!/bin/csh -f

set output = california_d.eps

# Small map
set x1 = -124
set x2 = -122
set y1 = 39.4
set y2 = 41.8
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.0/40.6/5.0

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -X7 -Y5 -P -K >! $output

gmt psxy plourde.txt -R$Rop -J$Jop -Sc -Crgb -O -K >> $output

# Large map
set x1 = -130
set x2 = -116
set y1 = 35
set y2 = 47
set Rop = $x1/$x2/$y1/$y2
set Jop = m-122.95/40.6/0.5

gmt pscoast -R$Rop -J$Jop -Ba5f2.5:a2.5f1.25:WESN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X-5 -Y-1 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-124 41.8
-122 41.8
-122 39.4
-124 39.4
-124 41.8
END

gmt psxy zoom.dat -R$Rop -J$Jop -Wthicker,black -O -K >> $output

cat << END >> names.dat
-127 41 Cape
-127 39.5 Mendocino
END

gmt pstext names.dat -R$Rop -J$Jop -F+f12p,black -O -K >> $output

gmt psscale -Crgb -D7/-1.5/10/0.3h -O -L -B:"Fractional index": >> $output

rm *.dat
