#!/bin/csh -f

set output = cascadia_d.eps

# Small map
set x1 = -124.25
set x2 = -122.25
set y1 = 47.5
set y2 = 48.5
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.25/48/10.0

# Coastline
gmt pscoast -R$Rop -J$Jop -Ba0.5f0.25:a0.25f0.125:WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -X5 -Y5 -P -K >! $output

gmt psxy sweet.txt -R$Rop -J$Jop -Sc -Crgb -O -K >> $output

gmt psxy chestler.txt -R$Rop -J$Jop -Sc -Crgb -O -K >> $output

# Large map
set x1 = -130
set x2 = -116
set y1 = 43.5
set y2 = 51.5
set Rop = $x1/$x2/$y1/$y2
set Jop = m-122.75/48/0.7

gmt pscoast -R$Rop -J$Jop -Ba5f2.5:a2.5f1.25:WESN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X-3 -Y-1 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-124.25 48.5
-122.25 48.5
-122.25 47.5
-124.25 47.5
-124.25 48.5
END

gmt psxy zoom.dat -R$Rop -J$Jop -Wthicker,black -O -K >> $output

cat << END >> names.dat
-120 48.5 Olympic
-120 47.5 Peninsula
END

gmt pstext names.dat -R$Rop -J$Jop -F+f12p,black -O -K >> $output

gmt psscale -Crgb -D8/-1.5/10/0.3h -O -L -B:"Fractional index": >> $output

rm *.dat
