#!/bin/csh -f

set output = guerrero_d.eps

# Small map
set x1 = -101
set x2 = -98.5
set y1 = 17.5
set y2 = 19.6
set Rop = $x1/$x2/$y1/$y2
set Jop = m-99.75/18.55/5.0

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -X6 -Y5 -P -K >! $output

gmt psxy frank.txt -R$Rop -J$Jop -Sc -Crgb -O -K >> $output

# Large map
set x1 = -107
set x2 = -93
set y1 = 12
set y2 = 25
set Rop = $x1/$x2/$y1/$y2
set Jop = m-99.75/18.5/0.4

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::WESN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X-4 -Y-1 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-101.0 17.5
-101.0 19.5
-98.5  19.5
-98.5  17.5
-101.0 17.5
END

gmt psxy zoom.dat -R$Rop -J$Jop -Wthicker,black -O -K >> $output

cat << END >> names.dat
-99.75 16 Guerrero
END

gmt pstext names.dat -R$Rop -J$Jop -F+f12p,black -O -K >> $output

gmt psscale -Crgb -D7/-1.5/10/0.3h -O -L -B:"Fractional index": >> $output

rm *.dat
