#!/bin/csh -f

set output = sanandreas_d.eps

# Small map
set x1 = -121.3
set x2 = -119.9
set y1 = 35.4
set y2 = 36.5
set Rop = $x1/$x2/$y1/$y2
set Jop = m-120.6/35.95/10.0

# Coastline
gmt pscoast -R$Rop -J$Jop -Ba0.5f0.25:a0.25f0.125:WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -X5 -Y5 -P -K >! $output

gmt psxy shelly.txt -R$Rop -J$Jop -Sc -Crgb -O -K >> $output

# Large map
set x1 = -127
set x2 = -113
set y1 = 32
set y2 = 42
set Rop = $x1/$x2/$y1/$y2
set Jop = m-120.6/35.95/0.5

gmt pscoast -R$Rop -J$Jop -Ba5f2.5:a2.5f1.25:WESN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X-3 -Y-1 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-121.3 35.4
-121.3 36.6
-119.9 36.6
-119.9 35.4
-121.3 35.4
END

gmt psxy zoom.dat -R$Rop -J$Jop -Wthicker,black -O -K >> $output

cat << END >> names.dat
-124.5 36 Parkfield
END

gmt pstext names.dat -R$Rop -J$Jop -F+f12p,black -O -K >> $output

gmt psscale -Crgb -D7/-1.5/10/0.3h -O -L -B:"Fractional index": >> $output

rm *.dat
