#!/bin/csh -f

set output = california.eps

# Small map
set x1 = -126
set x2 = -122
set y1 = 38
set y2 = 42
set Rop = $x1/$x2/$y1/$y2
set Jop = m-124/40/5.0

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

gmt psxy plourde.txt -R$Rop -J$Jop -Sc0.2 -Gred -O -K >> $output

# Large map
set x1 = -130
set x2 = -116
set y1 = 35
set y2 = 47
set Rop = $x1/$x2/$y1/$y2
set Jop = m-124/40/0.8

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::wEsN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X0.5 -Y0.5 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-123 40.5
END

cat << END >> names.dat
-126 41 Cape
-126 40 Mendocino
END

gmt psxy zoom.dat -R$Rop -J$Jop -Sc0.4 -Gred -O -K >> $output

gmt pstext names.dat -R$Rop -J$Jop -F+f15p,red -O >> $output

rm names.dat
rm zoom.dat
