#!/bin/csh -f

set output = cascadia.eps

# Small map
set x1 = -124
set x2 = -122
set y1 = 46.5
set y2 = 48.5
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123/47.5/11.0

gmt pscoast -R$Rop -J$Jop -Ba0.5f0.25::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

gmt psxy chestler.txt -R$Rop -J$Jop -Sc0.2 -Gred -O -K >> $output

gmt psxy sweet.txt -R$Rop -J$Jop -Sc0.2 -Gblue -O -K >> $output

# Large map
set x1 = -130
set x2 = -116
set y1 = 43.5
set y2 = 51.5
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123/47.5/1.0

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::wEsN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X0.5 -Y0.5 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-123 48
END

cat << END >> names.dat
-120 48.5 Olympic
-120 47.5 Peninsula
END

gmt psxy zoom.dat -R$Rop -J$Jop -Sc0.4 -Gred -O -K >> $output

gmt pstext names.dat -R$Rop -J$Jop -F+f15p,red -O >> $output

rm names.dat
rm zoom.dat
