#!/bin/csh -f

set output = sanandreas.eps

# Small map
set x1 = -123
set x2 = -119
set y1 = 33
set y2 = 37
set Rop = $x1/$x2/$y1/$y2
set Jop = m-121/35/5.0

gmt pscoast -R$Rop -J$Jop -Ba1f0.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

gmt psxy shelly.txt -R$Rop -J$Jop -Sc0.2 -Gred -O -K >> $output

# Large map
set x1 = -127
set x2 = -113
set y1 = 32
set y2 = 42
set Rop = $x1/$x2/$y1/$y2
set Jop = m-121/35/0.9

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::wEsN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X0.5 -Y0.5 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-120.5 36
END

cat << END >> names.dat
-122.5 36 Parkfield
END

gmt psxy zoom.dat -R$Rop -J$Jop -Sc0.4 -Gred -O -K >> $output

gmt pstext names.dat -R$Rop -J$Jop -F+f15p,red -O >> $output

rm names.dat
rm zoom.dat
