#!/bin/csh -f

set output = newzealand.eps

# Small map
set x1 = 165
set x2 = 180
set y1 = -48
set y2 = -34
set Rop = $x1/$x2/$y1/$y2
set Jop = m172.5/-41/1.5

gmt pscoast -R$Rop -J$Jop -Ba5f2.5::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

# Location of Wellington
cat << END >> points.dat
174.77557 -41.28664
END

cat << END >> names.dat
176.27557 -41.78664 Wellington
178 -36 North Island
168 -43 South Island
169 -38 Australian Plate
177 -45 Pacific Plate
END

gmt psxy points.dat -R$Rop -J$Jop -Sc0.4 -Gblack -O -K >> $output

gmt pstext names.dat -R$Rop -J$Jop -F+f20p -O -K >> $output

# Location of small map
cat << END >> zoom.dat
177.5 -38.5
END

cat << END >> trench.dat
177.5 -38 Northern
177.5 -39 Hikurangi
END

gmt psxy zoom.dat -R$Rop -J$Jop -Sc4 -Wfat,red -O -K >> $output

gmt pstext trench.dat -R$Rop -J$Jop -F+f20p,red -O >> $output

rm names.dat
rm points.dat
rm trench.dat
rm zoom.dat
