#!/bin/csh -f

set output = grid_location.eps

# Small map
set x1 = -123.9
set x2 = -122.5
set y1 = 47.6
set y2 = 48.4
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.2/48.0/18.0

gmt pscoast -R$Rop -J$Jop -Ba0.25f0.125::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y5 -P -K >! $output

# Locations of arrays
cat << END >> arrays.dat
-122.92866 47.95728
END

# Names of arrays
cat << END >> names.dat
-122.92866 47.93728 Big Skidder
END

gmt psxy arrays.dat -R$Rop -J$Jop -St0.8 -Gred -O -K >> $output

gmt pstext names.dat -R$Rop -J$Jop -F+f12p -O -K >> $output

gmt psxy coordinates.txt -R$Rop -J$Jop -Sc0.3 -Gblack -O >> $output

rm arrays.dat
rm names.dat
