#!/bin/csh -f

set output = cascadia.eps

# Small map
set x1 = -124.25
set x2 = -122.25
set y1 = 47.5
set y2 = 48.5
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.25/48/10.0

# Coastline
gmt pscoast -R$Rop -J$Jop -Ba0.5f0.25:a0.25f0.125:WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -X5 -Y5 -P -K >! $output

# Location of LFE families
cat << END >> locations.dat
-123.28 47.88
-122.98 47.97
-122.83 47.99
-122.62 47.88
END

gmt psxy locations.dat -R$Rop -J$Jop -Sc0.2 -Gred -O -K >> $output

# Legend: recurrence time
cat << END >> arrows.dat
-123.33 47.905 -0.707 0.707 0.0 0.0 1.0
-123.005 47.995 -0.5 0.866 0.0 0.0 1.0
-122.805 48.015 0.5 0.866 0.0 0.0 1.0
-122.57 47.905 0.707 0.707 0.0 0.0 1.0
END

gmt psvelo arrows.dat -R$Rop -J$Jop -W1p,black -Se1.5/0.8/1.0 -A+ba+gblack -O -K >> $output

cat << END >> times.dat
-123.53 48.055 416 days
-123.15 48.17 151 days
-122.68 48.19 58 days
-122.37 48.055 8 days
END

gmt pstext times.dat -R$Rop -J$Jop -F+f12p,black -O -K >> $output

# Large map
set x1 = -130
set x2 = -116
set y1 = 43.5
set y2 = 51.5
set Rop = $x1/$x2/$y1/$y2
set Jop = m-122.75/48/0.7

gmt pscoast -R$Rop -J$Jop -Ba5f2.5:a2.5f1.25:WESN -W0.1p -S224/255/255 -G255/255/224 -Dl -Na -X-3 -Y-1 -O -K >> $output

# Location of small map
cat << END >> zoom.dat
-124.25 48.5
-122.25 48.5
-122.25 47.5
-124.25 47.5
-124.25 48.5
END

gmt psxy zoom.dat -R$Rop -J$Jop -Wthicker,black -O -K >> $output

cat << END >> names.dat
-120 48.5 Olympic
-120 47.5 Peninsula
END

gmt pstext names.dat -R$Rop -J$Jop -F+f12p,black -O >> $output

rm *.dat

