#!/bin/csh -f

set output = portangeles.eps

# Small map
set x1 = -125
set x2 = -122
set y1 = 47
set y2 = 49.2
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.5/48.1/8.0

gmt pscoast -R$Rop -J$Jop -Ba0.5f0.25::WESN -W0.1p -G255/255/224 -S224/255/255 -Lf-123.25/47.25/48.1/100 -Df -Na -Y5 -P -K >! $output

# Locations of GPS stations
cat << END >> GPS.dat
-123.2915 48.2323
-122.7759 48.0106
-122.6856 48.2173
-123.4511 48.6483
-123.0076 48.5462
-123.7057 47.8166
-122.6670 47.7550
-123.0180 48.5352
-123.4152 48.1014
-123.1020 48.0823
END

# Names of GPS stations
cat << END >> names.dat
-123.2915 48.1823 ALBH
-122.7759 47.9606 CHCM
-122.6856 48.1673 COUP
-123.4511 48.5983 PGC5
-123.0076 48.5962 SC02
-123.7057 47.7666 SC03
-122.6670 47.7050 UFDA
-123.0180 48.4852 FRID
-123.4152 48.0514 PNCL
-123.1020 48.0323 SQIM
END

gmt psxy tremor_all.dat -R$Rop -J$Jop -Sc0.03 -Ggrey -O -K >> $output

#gmt psxy 10-12_10_2009.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 09-13_11_2009.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 21-23_01_2010.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 01-03_02_2010.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 16-21_03_2010.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 25-31_03_2010.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
gmt psxy 31_12_2010-03_01_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 22-23_01_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 13_03_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 27_04-01_05_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 21_05_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 21_06_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 28-30_06_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output
#gmt psxy 13-14_12_2011.dat -R$Rop -J$Jop -Sc0.1 -Gred -O -K >> $output

gmt pscoast -R$Rop -J$Jop -Ba0.5f0.25::WESN -W0.1p -Lf-123.25/47.25/48.1/100 -Df -Na -O -K >> $output

cat << END >> mytext.dat
-123.25 47.3 km
END

gmt pstext mytext.dat -R$Rop -J$Jop -F+f15p -O -K >> $output

rm mytext.dat

gmt psxy GPS.dat -R$Rop -J$Jop -St0.4 -Gblack -O -K >> $output

gmt pstext names.dat -R$Rop -J$Jop -F+f12p -O -K >> $output

# Large map
set x1 = -130
set x2 = -120
set y1 = 44
set y2 = 52
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.5/48.1/1

gmt pscoast -R$Rop -J$Jop -Ba2f1::WESN -W0.1p -G255/255/224 -S224/255/255 -Lf-125/45/48.1/200 -Df -Na -X-1.5 -Y-1.5 -O -K >> $output

cat << END >> mytext.dat
-125 45.3 km
END

gmt pstext mytext.dat -R$Rop -J$Jop -F+f12p -O -K >> $output

rm mytext.dat

# Limits of small map
cat << END >> square.dat
-125 47
-125 49.2
-122 49.2
-122 47
-125 47
END

gmt psxy square.dat -R$Rop -J$Jop -Wthicker,black -O >> $output

rm GPS.dat
rm names.dat
rm square.dat
